# Site settings
title: Ray Blog
SEOTitle: 家瑞的博客 | Ray Blog
header-img: img/post-bg-desk.jpg
email: jary328@qq.com
description: "Progress is the activity of today and the assurance of tomorrow."
keyword: "Ray, Ray Blog, 家瑞的博客, liujiarui, 刘家瑞, 前端, Javascript"
url: "http://rayure.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/rayure/rayure.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "All that you do, do with your might; things done by halves are never done right."
sidebar-avatar: /img/about-Ray-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     rayure
github_username:    rayure
# facebook_username:  ray
# jianshu_username:   ray
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# gitalk:
#   enable: true    #是否开启Gitalk评论
#   clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#   clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#   repo: qiubaiying.github.io    #仓库名称
#   owner: qiubaiying    #github用户名
#   admin: qiubaiying
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
  {
    title: "MDN web docs",
    href: "https://developer.mozilla.org/zh-CN/"
  }
]
